export interface WorkflowGuideData {
  id: string;
  stepNumber: number;
  title: string;
  shortTitle: string;
  badge: string;
  description: string;
  whatHappens: string[];
  whatYouNeed: string[];
  howUdyogSathiHelps: string[];
  exampleScenario: string;
  outcome: string;
  disclaimer?: string;
  prevStepId: string | null;
  nextStepId: string | null;
  authenticatedRoute: string;
}

export const WORKFLOW_GUIDES: Record<string, WorkflowGuideData> = {
  discover: {
    id: 'discover',
    stepNumber: 1,
    title: 'Discover the approvals your business may need',
    shortTitle: 'Discover',
    badge: 'Step 1 of 8 • Discovery & Identification',
    description:
      'Begin by describing your proposed industrial unit. UdyogSathi evaluates your sector, location, investment scale, pollution category, and utility requirements to map applicable statutory approvals.',
    whatHappens: [
      'Enter enterprise details (organisation name, legal entity type, investment amount).',
      'Select Maharashtra district, taluka, and location zoning (MIDC Industrial Area vs Non-MIDC).',
      'Specify manufacturing process, workforce count, water requirements, and environmental pollution category.',
      'Database-driven rule engine evaluates parameters against Maharashtra industrial acts.',
      'Identifies required department approvals, registrations, licences, and statutory NOCs.',
    ],
    whatYouNeed: [
      'Proposed enterprise name & legal structure (Proprietorship, Partnership, LLP, Pvt Ltd).',
      'Location details (District, Taluka, Plot size in Sq. Mtr.).',
      'Estimated capital investment & expected employee count.',
      'Power requirement (KW), Water requirement (KLD), and Wastewater volume.',
      'Environmental pollution classification (White, Green, Orange, Red).',
    ],
    howUdyogSathiHelps: [
      'Eliminates guesswork by auto-detecting statutory requirements in under 2 minutes.',
      'Explains why each approval applies based on specific legislative mandates.',
      'Groups approvals logically by project stage (Pre-establishment vs Pre-operation).',
      'Shows competent state department (MIDC, MPCB, DISH, Fire Dept, Labour).',
      'Calculates estimated SLA timelines and statutory fees upfront.',
    ],
    exampleScenario:
      'Example: Vijay Kulkarni plans to establish Vijay Foods & Agro Processing Pvt. Ltd. at Chakan Phase II, Pune MIDC with ₹4.5 Crore investment. UdyogSathi instantly identifies 5 required approvals: MIDC Land Allotment, MPCB Consent to Establish (CTE), DISH Factory Building Plan Approval, Provisional Fire NOC, and MIDC Water Connection.',
    outcome:
      'You receive a complete, transparent statutory approval roadmap tailored specifically to your industrial project.',
    disclaimer:
      'Approval discovery guidance is generated by database rules. Final statutory jurisdiction rests with competent state government authorities.',
    prevStepId: null,
    nextStepId: 'prepare',
    authenticatedRoute: '/approval-wizard',
  },

  prepare: {
    id: 'prepare',
    stepNumber: 2,
    title: 'Prepare your requirements and document checklist',
    shortTitle: 'Prepare',
    badge: 'Step 2 of 8 • Checklist & Document Prep',
    description:
      'Once required approvals are identified, UdyogSathi generates an itemised document checklist and information requirements for each statutory application.',
    whatHappens: [
      'View individual approval requirements broken down by issuing authority.',
      'Review mandatory documents, legal annexures, architectural drawings, and engineering reports.',
      'Identify common documents shared across multiple department applications.',
      'Check statutory SLA service timelines (e.g. MPCB CTE: 45 days, DISH Plan Approval: 30 days).',
      'Organise files before commencing application submission.',
    ],
    whatYouNeed: [
      'Promoter Permanent Account Number (PAN) Card.',
      'Goods and Services Tax (GST) Registration Certificate.',
      'Certificate of Incorporation (COI) / Partnership Deed.',
      'Registered Office Address Proof (Utility bill / MIDC allotment letter).',
      'MIDC Plot Lease Allotment Deed / 7-12 Land Extract.',
      'Architectural Factory Layout Plan & ETP Water Balance Report (where applicable).',
    ],
    howUdyogSathiHelps: [
      'Cross-checks required documents to prevent incomplete application submissions.',
      'Highlights reusable documents that can be uploaded once and shared.',
      'Displays risk levels and department scrutiny SLAs for planning project timelines.',
      'Provides downloadable PDF checklists for offline reference.',
    ],
    exampleScenario:
      'Example: For MPCB Consent to Establish, Vijay sees he needs 4 documents: Promoter PAN, GST Certificate, Company Incorporation Certificate, and MIDC Land Deed. All 4 documents are also required by DISH and MIDC, enabling 1-click document reuse.',
    outcome:
      'You know exactly which documents to gather before starting any application, eliminating back-and-forth queries.',
    prevStepId: 'discover',
    nextStepId: 'upload-once',
    authenticatedRoute: '/projects',
  },

  'upload-once': {
    id: 'upload-once',
    stepNumber: 3,
    title: 'Upload important documents once to your Document Vault',
    shortTitle: 'Upload Once',
    badge: 'Step 3 of 8 • Verified Document Vault',
    description:
      'Store key enterprise documents securely in your encrypted Document Vault. UdyogSathi runs AI pre-validation to verify file readiness and enables 1-click document reuse across eligible applications.',
    whatHappens: [
      'Upload business documents once to your secure enterprise vault.',
      'AI assistant pre-validates metadata, file readability, address alignment, and expiry dates.',
      'Documents are submitted for officer verification or stored as verified vault records.',
      'Verified documents become eligible for 1-click auto-linking in statutory applications.',
      'Track document versioning, expiry warnings (30/60/90 days), and usage history.',
    ],
    whatYouNeed: [
      'PAN Card (PDF / Image format, max 5 MB).',
      'GST Certificate (PDF format).',
      'Incorporation Certificate / MOA & AOA.',
      'Address Proof (Electricity bill / Land Deed).',
      'Authorised Signatory Letter / Board Resolution.',
    ],
    howUdyogSathiHelps: [
      'Eliminates duplicate file uploads across multiple government departments.',
      'AI pre-validation catches expired or mismatching documents before submission.',
      'Maintains full audit logs of document usage across applications.',
      'Reduces application preparation effort by up to 78%.',
    ],
    exampleScenario:
      'Example: Vijay uploads his MSEDCL Electricity Bill as Address Proof. The AI pre-validator confirms 95% readiness score. When applying for MPCB CTE, DISH Building Approval, and MIDC Water Connection, Vijay clicks "Reuse All Eligible Documents" to attach the same verified file instantly.',
    outcome:
      'Your verified Document Vault is ready to power 1-click statutory application submissions.',
    disclaimer:
      'AI pre-validation assists document readiness. Final statutory verification remains with authorised department officers.',
    prevStepId: 'prepare',
    nextStepId: 'apply',
    authenticatedRoute: '/vault',
  },

  apply: {
    id: 'apply',
    stepNumber: 4,
    title: 'Fill and submit applications from one workspace',
    shortTitle: 'Apply',
    badge: 'Step 4 of 8 • Single Window Applications',
    description:
      'Complete and submit statutory approval applications directly from your single-window workspace. Reusable data and verified vault documents pre-fill automatically.',
    whatHappens: [
      'Select required approval from your project checklist.',
      'Open pre-filled application form with enterprise and project parameters.',
      'Attach reusable vault documents with 1 click or upload approval-specific files.',
      'Perform readiness check to confirm 100% submission compliance.',
      'Submit application to the single-window department review queue.',
    ],
    whatYouNeed: [
      'Completed project parameters & verified vault documents.',
      'Approval-specific technical attachments (e.g. ETP Capacity Report for MPCB).',
      'Authorised signatory digital confirmation.',
    ],
    howUdyogSathiHelps: [
      'Single-window application forms auto-populate enterprise data to avoid repetitive entry.',
      'Validates all mandatory fields before submission to ensure zero returns for incompleteness.',
      'Generates unique Application Reference Numbers (e.g. APP-2026-8801).',
      'Routes applications instantly to competent department scrutiny queues.',
    ],
    exampleScenario:
      'Example: Vijay opens the Factory Building Plan Approval application for DISH. The form auto-fills Vijay Foods Pvt Ltd, Chakan plot details, and attaches 3 verified vault documents. Vijay clicks Submit and receives reference number APP-2026-8802.',
    outcome:
      'Your application enters the structured department scrutiny workflow with official tracking.',
    disclaimer:
      'Submissions enter single-window department workflow reviews. Final statutory decisions remain with competent authorities.',
    prevStepId: 'upload-once',
    nextStepId: 'track',
    authenticatedRoute: '/applications',
  },

  track: {
    id: 'track',
    stepNumber: 5,
    title: 'Track your application progress in real time',
    shortTitle: 'Track',
    badge: 'Step 5 of 8 • SLA & Query Tracker',
    description:
      'Monitor scrutiny status, department officer queries, service-level agreement (SLA) countdowns, andNext Actions from a single unified tracking dashboard.',
    whatHappens: [
      'View real-time status updates across all submitted applications.',
      'Track statutory SLA days remaining (e.g. 18 days remaining of 30-day SLA).',
      'Receive instant SMS / Email notifications when department officers raise queries.',
      'Submit query clarifications and supplementary documents directly online.',
      'View complete audit history of department scrutiny events.',
    ],
    whatYouNeed: [
      'Application Reference Number.',
      'Registered email/mobile for real-time notification alerts.',
    ],
    howUdyogSathiHelps: [
      'Provides 100% transparency into officer scrutiny and queue placement.',
      'Alerts applicants immediately when a query is raised to prevent SLA clock expiry.',
      'Automates escalation for SLA delay bottlenecks.',
      'Eliminates physical visits to government department offices.',
    ],
    exampleScenario:
      'Example: An MPCB officer scrutinising Vijay\'s CTE application raises a query requesting ETP water balance calculations. Vijay receives an instant notification, views the query on his dashboard, uploads the ETP calculation sheet, and submits the response within 2 hours.',
    outcome:
      'You maintain full visibility and control over your approval timeline without delays.',
    prevStepId: 'apply',
    nextStepId: 'inspection',
    authenticatedRoute: '/applications',
  },

  inspection: {
    id: 'inspection',
    stepNumber: 6,
    title: 'Coordinate field inspections with complete clarity',
    shortTitle: 'Inspection',
    badge: 'Step 6 of 8 • Inspection Management',
    description:
      'Coordinate scheduled site inspections with department inspectors. Track inspection dates, officer details, geofenced evidence capture, and official inspection reports.',
    whatHappens: [
      'Department officer schedules mandatory field inspection for site verification.',
      'Applicant receives inspection appointment date, inspector name, and checklist.',
      'Authorised inspector visits site and logs digital observations.',
      'Geofenced camera evidence is uploaded by the inspector.',
      'Official inspection report is attached to the application file.',
    ],
    whatYouNeed: [
      'Site readiness as per statutory inspection checklist.',
      'Authorised representative present at factory/site during scheduled window.',
      'Land boundary markings & building layout drawings available on site.',
    ],
    howUdyogSathiHelps: [
      'Eliminates surprise inspections by providing advance appointment notifications.',
      'Provides transparent inspection checklists so applicants know what will be verified.',
      'Connects field inspection reports directly to the department decision workflow.',
      'Ensures geofenced evidence integrity for fast officer decision-making.',
    ],
    exampleScenario:
      'Example: DISH Inspector Rajendra Deshmukh is assigned to inspect Vijay\'s Chakan plot for building safety. Vijay receives an inspection alert for 05 Sep 2026. On the date, Inspector Rajendra completes the audit and uploads geotagged camera evidence.',
    outcome:
      'Site inspections are conducted transparently and recorded digitally in your file.',
    disclaimer:
      'Camera and location permissions are requested only when an authorised inspector explicitly captures field evidence.',
    prevStepId: 'track',
    nextStepId: 'decision',
    authenticatedRoute: '/inspections',
  },

  decision: {
    id: 'decision',
    stepNumber: 7,
    title: 'Receive and understand statutory department decisions',
    shortTitle: 'Decision',
    badge: 'Step 7 of 8 • Official Decision',
    description:
      'Receive official statutory decisions from competent department authorities. View approval certificates, conditional clearance terms, or correction requirements.',
    whatHappens: [
      'Competent authority records final decision (Approved, Rejected, Returned for Correction).',
      'Applicant receives instant decision notification and digital certificate access.',
      'Approved certificates are automatically archived in your Document Vault.',
      'Returned applications display specific correction instructions and re-submission links.',
      'Approved clearances trigger automatic compliance calendar entries.',
    ],
    whatYouNeed: [
      'Application Reference Number.',
    ],
    howUdyogSathiHelps: [
      'Delivers formal statutory decisions digitally without physical collection.',
      'Explains rejection or return reasons in plain language with actionable next steps.',
      'Automatically logs validity periods and renewal dates for approved certificates.',
      'Provides access to grievance escalation if decisions breach statutory SLA limits.',
    ],
    exampleScenario:
      'Example: DISH issues Certificate DISH/PN/2026/FPA-4491 approving Vijay\'s Factory Building Plan. The certificate is stored in Vijay\'s vault and automatically added to his compliance calendar.',
    outcome:
      'You receive a clear, legally documented decision and understand your next compliance steps.',
    disclaimer:
      'Application decisions reflect statutory department reviews. Final authority remains with competent state government departments.',
    prevStepId: 'inspection',
    nextStepId: 'continue',
    authenticatedRoute: '/applications',
  },

  continue: {
    id: 'continue',
    stepNumber: 8,
    title: 'Continue with compliance, renewals, schemes, and support',
    shortTitle: 'Continue',
    badge: 'Step 8 of 8 • Compliance & Growth',
    description:
      'Approval is just the beginning. UdyogSathi provides automated compliance calendars, 1-click renewal alerts, government scheme matching, and grievance support for operational enterprise growth.',
    whatHappens: [
      'Compliance Calendar tracks upcoming periodic filings, returns, and licence renewals.',
      'Automated reminders notify you at 90, 60, 30, and 7 days before licence expiry.',
      'Execute 1-Click Renewals using pre-validated vault documents.',
      'Discover matching Maharashtra & Central government incentive schemes (e.g. MSINS Subsidy, Power Tariff Concession).',
      'Raise and escalate grievances for service delays or departmental issues.',
    ],
    whatYouNeed: [
      'Active industrial enterprise profile & issued statutory clearances.',
    ],
    howUdyogSathiHelps: [
      'Prevents costly penalty fees and business disruption from expired licences.',
      'Enables 1-click renewal applications by reusing existing verified vault documents.',
      'Matches your enterprise parameters with eligible financial subsidies and incentives.',
      'Provides a dedicated grievance helpdesk with automated escalation triggers.',
    ],
    exampleScenario:
      'Example: 30 days before Vijay\'s MPCB Consent to Operate expires, UdyogSathi sends a renewal alert. Vijay clicks "1-Click Renewal", attaches his verified vault docs, and submits the CTO renewal in under 2 minutes.',
    outcome:
      'Your enterprise maintains 100% ongoing compliance while unlocking government support schemes.',
    prevStepId: 'decision',
    nextStepId: null,
    authenticatedRoute: '/compliance',
  },
};
