'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { TopUtilityBar } from '@/components/layout/TopUtilityBar';
import { OfficialHeader } from '@/components/layout/OfficialHeader';
import { Footer } from '@/components/layout/Footer';
import { DisclaimerBanner } from '@/components/common/DisclaimerBanner';
import { getTranslation } from '@/lib/i18n';
import { ROUTES } from '@/lib/routes';
import { HelpCircle, ChevronDown, ChevronUp, Search, Home, ArrowRight } from 'lucide-react';

export default function FAQPage() {
  const [currentLang, setCurrentLang] = useState('en');
  const [activeFaq, setActiveFaq] = useState<number | null>(0);
  const [searchQuery, setSearchQuery] = useState('');

  const faqs = [
    {
      q: 'How does UdyogSathi AI determine which approvals apply to my industrial project?',
      a: 'The platform evaluates your project parameters — including sector, investment amount, district, MIDC vs non-MIDC zoning, workforce size, water/waste requirements, and environmental pollution category (White, Green, Orange, Red) — against database-driven statutory rules based on Maharashtra industrial acts.',
    },
    {
      q: 'Are the approvals generated by UdyogSathi AI legally binding?',
      a: 'No. UdyogSathi AI is an informational decision-support and workflow management platform. Final eligibility, statutory compliance requirements, and approval decisions remain with the competent government authority.',
    },
    {
      q: 'How does the Document Vault Pre-Validation Assistant work?',
      a: 'When you upload documents to your vault, the assistant automatically verifies file formats, size limits, expiry dates, mandatory document presence, and metadata consistency, calculating a Submission Readiness Score before official scrutiny.',
    },
    {
      q: 'Is multi-language support available for Marathi, Hindi, and Indian regional languages?',
      a: 'Yes! UdyogSathi AI features full interface translation dictionaries for English, Marathi, Hindi, and Urdu (RTL), along with native script architecture across 23 official Indian languages.',
    },
    {
      q: 'What is the role of Field Inspectors on the portal?',
      a: 'Field Inspectors can access assigned site inspection tasks, perform live camera evidence photo capture with geolocation tagging, verify structural safety, and submit digital scrutiny reports directly into the workflow engine.',
    },
    {
      q: 'How can I match government incentive schemes for my MSME or Large unit?',
      a: 'Navigate to the Schemes & Incentives section to search eligible state policies such as Package Scheme of Incentives (PSI 2019), Electric Vehicle Policy, IT Policy, and Textile Subsidies tailored to your investment scale.',
    },
  ];

  const filteredFaqs = faqs.filter(
    f => f.q.toLowerCase().includes(searchQuery.toLowerCase()) || f.a.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="bg-[#f7f9fc] min-h-screen flex flex-col font-sans">
      <TopUtilityBar currentLang={currentLang} onLanguageChange={setCurrentLang} />
      <OfficialHeader currentLang={currentLang} />
      <DisclaimerBanner lang={currentLang} />

      <main id="main-content" className="flex-1 py-10 px-4 max-w-4xl mx-auto w-full space-y-6">
        {/* Title */}
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-govBorder pb-4">
          <div>
            <div className="flex items-center gap-2 text-xs text-govMuted mb-1">
              <Link href={ROUTES.home} className="hover:text-govBlue flex items-center gap-1">
                <Home className="w-3.5 h-3.5" />
                <span>Home</span>
              </Link>
              <span>/</span>
              <span className="font-semibold text-govBlue">FAQs</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-govBlue tracking-tight flex items-center gap-2">
              <HelpCircle className="w-7 h-7 text-saffron" />
              <span>Frequently Asked Questions (FAQs)</span>
            </h1>
            <p className="text-xs text-govMuted mt-1">
              Find instant answers regarding statutory approvals, document pre-validation, inspections, and portal features.
            </p>
          </div>

          <Link
            href={ROUTES.home}
            className="inline-flex items-center gap-1.5 text-xs font-bold text-govBlue hover:bg-govBlue-50 px-3 py-2 rounded-lg border border-govBlue/20 transition-colors"
          >
            <Home className="w-4 h-4" />
            <span>Back to Home</span>
          </Link>
        </div>

        {/* Search */}
        <div className="relative">
          <Search className="w-4 h-4 absolute left-3.5 top-3 text-slate-400" />
          <input
            type="text"
            placeholder="Search FAQs..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 text-xs border border-slate-300 rounded-xl focus:ring-2 focus:ring-saffron focus:outline-none bg-white shadow-sm"
          />
        </div>

        {/* Accordions */}
        <div className="space-y-3">
          {filteredFaqs.map((faq, idx) => (
            <div key={idx} className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
              <button
                onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                className="w-full text-left p-4 text-xs font-bold text-govBlue flex items-center justify-between bg-slate-50 hover:bg-slate-100 transition-colors"
              >
                <span>{faq.q}</span>
                {activeFaq === idx ? <ChevronUp className="w-4 h-4 text-saffron shrink-0" /> : <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />}
              </button>
              {activeFaq === idx && (
                <div className="p-4 text-xs text-slate-700 bg-white border-t border-slate-100 leading-relaxed animate-fadeIn">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="bg-govBlue text-white p-6 rounded-2xl shadow-md flex flex-wrap items-center justify-between gap-4">
          <div>
            <h3 className="text-base font-bold">Have More Questions About Industrial Clearances?</h3>
            <p className="text-xs text-slate-200 mt-1">Use our interactive Discovery Wizard to analyze your project specifications.</p>
          </div>
          <Link
            href={ROUTES.approvalWizard}
            className="bg-saffron hover:bg-saffron-dark text-white text-xs font-bold px-4 py-2.5 rounded-lg shadow flex items-center gap-1.5"
          >
            <span>Launch Approval Wizard</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
