'use client';

import React, { useState } from 'react';
import { TopUtilityBar } from '@/components/layout/TopUtilityBar';
import { OfficialHeader } from '@/components/layout/OfficialHeader';
import { Footer } from '@/components/layout/Footer';
import { DisclaimerBanner } from '@/components/common/DisclaimerBanner';
import { AlertTriangle, Info, ShieldCheck } from 'lucide-react';

export default function StatutoryDisclaimerPage() {
  const [currentLang, setCurrentLang] = useState('en');

  return (
    <div className="bg-[#f7f9fc] min-h-screen flex flex-col font-sans text-govText">
      <TopUtilityBar currentLang={currentLang} onLanguageChange={setCurrentLang} />
      <OfficialHeader currentLang={currentLang} />
      <DisclaimerBanner lang={currentLang} />

      <main className="flex-1 py-8 px-4 max-w-4xl mx-auto w-full space-y-6">
        <div className="bg-white p-6 md:p-8 rounded-2xl border border-govBorder shadow-sm space-y-6 text-xs leading-relaxed">
          <div className="border-b pb-4">
            <span className="text-saffron font-bold text-xs uppercase tracking-wider block">
              Official Statutory Notice
            </span>
            <h1 className="text-2xl font-extrabold text-govBlue mt-1">Statutory Disclaimer & Guidance Notice</h1>
            <p className="text-slate-500 mt-1">Last Updated: September 2026</p>
          </div>

          <div className="bg-amber-50 border border-amber-300 p-4 rounded-xl flex items-start gap-3 text-amber-950">
            <AlertTriangle className="w-5 h-5 text-saffron shrink-0 mt-0.5" />
            <div>
              <span className="font-extrabold block text-govBlue">Guidance & Information Disclaimer</span>
              <span>
                Roadmaps generated by UdyogSathi AI provide statutory guidance based on project parameters submitted by the entrepreneur. This guidance does not constitute a legal determination or statutory clearance in itself. Final approval authority resides exclusively with competent state department officers (MPCB, DISH, MIDC, Revenue).
              </span>
            </div>
          </div>

          <section className="space-y-3">
            <h2 className="text-base font-bold text-govBlue flex items-center gap-2">
              <Info className="w-5 h-5 text-saffron" /> SLA & Pre-Validation Disclaimer
            </h2>
            <p>
              Demo SLA days and document pre-validation readiness scores are computational estimates designed to assist applicants. They do not guarantee statutory timeline completion where site inspections or officer query resolutions are pending.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
