'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { TopUtilityBar } from '@/components/layout/TopUtilityBar';
import { OfficialHeader } from '@/components/layout/OfficialHeader';
import { Footer } from '@/components/layout/Footer';
import { DisclaimerBanner } from '@/components/common/DisclaimerBanner';
import { MultiStepWizard } from '@/components/wizard/MultiStepWizard';
import { JourneyStepper } from '@/components/journey/JourneyStepper';
import { getTranslation } from '@/lib/i18n';
import { ROUTES } from '@/lib/routes';
import {
  Shield,
  Search,
  FileCheck,
  Building,
  Flame,
  Award,
  Zap,
  Droplet,
  Users,
  ArrowRight,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  Lock,
  Globe,
  HelpCircle,
  Sparkles,
  Layers,
} from 'lucide-react';

import { useAuth } from '@/context/AuthContext';

export default function LandingPage() {
  const { isAuthenticated } = useAuth();
  const [currentLang, setCurrentLang] = useState('en');
  const [activeFaq, setActiveFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does UdyogSathi determine which approvals apply to my industrial project?',
      a: 'The platform evaluates your project parameters — including sector, investment amount, district, MIDC vs non-MIDC zoning, workforce size, water/waste requirements, and environmental pollution category (White, Green, Orange, Red) — against database-driven statutory rules based on Maharashtra industrial acts.',
    },
    {
      q: 'Are the approvals generated by UdyogSathi legally binding?',
      a: 'UdyogSathi acts as a unified digital workflow platform for industrial approvals and compliance tracking. Application submissions, reviews, inspections, and decision records are managed through structured service workflows. Final statutory decisions remain with the competent authority.',
    },
    {
      q: 'How does the Document Vault Pre-Validation and Reuse Assistant work?',
      a: 'When you upload documents once to your vault, the system pre-validates metadata, file formats, and expiry dates. Once verified, eligible documents can be reused across multiple statutory applications with 1-click selection, avoiding duplicate uploads.',
    },
    {
      q: 'Is multi-language support available for Marathi and Hindi?',
      a: 'Yes! UdyogSathi features full interface translation dictionaries for English, Marathi, Hindi, and Urdu, along with localization architecture and native script support across 23 official Indian languages.',
    },
  ];

  return (
    <div className="bg-[#f7f9fc] min-h-screen flex flex-col font-sans">
      {/* Top Government Utility Bar */}
      <TopUtilityBar currentLang={currentLang} onLanguageChange={setCurrentLang} />

      {/* Official Department Header */}
      <OfficialHeader currentLang={currentLang} />

      {/* Mandatory Statutory Disclaimer Banner */}
      <DisclaimerBanner lang={currentLang} />

      <main id="main-content" className="flex-1">
        {/* HERO SECTION */}
        <section className="bg-gradient-to-b from-govBlue via-govBlue-dark to-slate-900 text-white py-16 px-4 relative overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(#E97721_1px,transparent_1px)] [background-size:24px_24px] opacity-10" />

          <div className="max-w-7xl mx-auto relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-7 space-y-6">
              <div className="inline-flex items-center gap-2 bg-saffron/20 text-saffron font-bold text-xs px-3 py-1 rounded-full border border-saffron/40">
                <Shield className="w-3.5 h-3.5" />
                <span>Single Window Industrial Workflow Layer • MSINS Initiative</span>
              </div>

              <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight leading-tight text-white">
                {getTranslation(currentLang, 'hero_headline')}
              </h1>

              <p className="text-sm md:text-base text-slate-300 leading-relaxed max-w-2xl">
                {getTranslation(currentLang, 'hero_subtext')}
              </p>

              {/* Value Proposition Badge */}
              <div className="bg-white/10 backdrop-blur-md p-3.5 rounded-xl border border-white/20 text-xs text-saffron font-semibold leading-relaxed flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-saffron shrink-0" />
                <span>{getTranslation(currentLang, 'value_prop')}</span>
              </div>

              {/* Primary & Secondary Action CTAs */}
              <div className="flex flex-wrap items-center gap-3 pt-2">
                {isAuthenticated ? (
                  <>
                    <Link
                      href={ROUTES.dashboard}
                      className="bg-saffron hover:bg-saffron-dark text-white px-6 py-3.5 rounded-xl font-extrabold text-sm flex items-center gap-2 shadow-xl transition-all hover:scale-105"
                    >
                      <Sparkles className="w-4 h-4" />
                      <span>Go to My Dashboard</span>
                      <ArrowRight className="w-4 h-4" />
                    </Link>

                    <Link
                      href={ROUTES.approvalWizard}
                      className="bg-white/10 hover:bg-white/20 text-white px-4 py-3.5 rounded-xl font-bold text-xs flex items-center gap-2 border border-white/30 transition-colors"
                    >
                      <Clock className="w-4 h-4 text-saffron" />
                      <span>Statutory Approval Roadmap Generator</span>
                    </Link>
                  </>
                ) : (
                  <>
                    <Link
                      href={ROUTES.approvalWizard}
                      className="bg-saffron hover:bg-saffron-dark text-white px-6 py-3.5 rounded-xl font-extrabold text-sm flex items-center gap-2 shadow-xl transition-all hover:scale-105"
                    >
                      <Sparkles className="w-4 h-4" />
                      <span>Statutory Approval Roadmap Generator</span>
                      <ArrowRight className="w-4 h-4" />
                    </Link>

                    <Link
                      href="/login"
                      className="bg-white/10 hover:bg-white/20 text-white px-4 py-3.5 rounded-xl font-bold text-xs flex items-center gap-2 border border-white/30 transition-colors"
                    >
                      <Lock className="w-4 h-4 text-saffron" />
                      <span>Sign In to Workspace</span>
                    </Link>
                  </>
                )}

                <Link
                  href={ROUTES.howItWorks}
                  className="text-slate-300 hover:text-white px-3 py-3.5 font-semibold text-xs flex items-center gap-1 transition-colors"
                >
                  <span>See How It Works</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            {/* Hero Quick Statistics KPI Card */}
            <div className="lg:col-span-5 bg-white text-govText p-6 rounded-2xl shadow-2xl border border-govBorder space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div>
                  <h3 className="text-sm font-bold text-govBlue">Single-Window Workflow Metrics</h3>
                  <span className="text-[11px] text-govMuted">Government of Maharashtra Sandbox</span>
                </div>
                <span className="bg-green-100 text-green-800 text-[10px] font-bold px-2 py-0.5 rounded border border-green-200">
                  Ready for Integration
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="bg-govBg p-3.5 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-govMuted font-semibold block">Connected Applications</span>
                  <div className="text-2xl font-extrabold text-govBlue mt-1">1,482</div>
                  <span className="text-[10px] text-govSuccess font-bold">1-Click Document Reuse</span>
                </div>

                <div className="bg-govBg p-3.5 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-govMuted font-semibold block">SLA Compliance Rate</span>
                  <div className="text-2xl font-extrabold text-govSuccess mt-1">94.8%</div>
                  <span className="text-[10px] text-govSuccess font-bold">Statutory SLA Tracked</span>
                </div>

                <div className="bg-govBg p-3.5 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-govMuted font-semibold block">Verified Vault Files</span>
                  <div className="text-2xl font-extrabold text-saffron mt-1">12,650</div>
                  <span className="text-[10px] text-saffron font-bold">78% Effort Reduction</span>
                </div>

                <div className="bg-govBg p-3.5 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-govMuted font-semibold block">Grievance Resolution</span>
                  <div className="text-2xl font-extrabold text-govBlue mt-1">99.2%</div>
                  <span className="text-[10px] text-blue-700 font-bold">Escalation Automated</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 8-STEP VISUAL JOURNEY STEPPER SECTION */}
        <section className="py-12 px-4 bg-white border-b border-govBorder">
          <div className="max-w-7xl mx-auto space-y-4">
            <JourneyStepper activeStep={1} lang={currentLang} />
          </div>
        </section>

        {/* WIZARD EMBEDDED SECTION */}
        <section className="py-16 px-4 bg-slate-100">
          <div className="max-w-7xl mx-auto">
            <div className="text-center max-w-2xl mx-auto mb-10">
              <span className="text-xs font-bold text-saffron uppercase tracking-widest">Interactive Discovery Engine</span>
              <h2 className="text-2xl md:text-3xl font-extrabold text-govBlue mt-1">
                Find Required Approvals & Statutory Checklists
              </h2>
              <p className="text-xs text-govMuted mt-2">
                Select your industrial sector, location, investment scale, and utility demand to generate your explainable statutory approval roadmap.
              </p>
            </div>

            <React.Suspense fallback={<div className="bg-white p-8 rounded-2xl border border-govBorder text-center text-xs font-bold text-govBlue">Loading Approval Wizard...</div>}>
              <MultiStepWizard />
            </React.Suspense>
          </div>
        </section>

        {/* FAQ SECTION */}
        <section className="py-16 px-4 bg-white">
          <div className="max-w-4xl mx-auto space-y-8">
            <div className="text-center space-y-2">
              <span className="text-xs font-bold text-saffron uppercase tracking-widest">Frequently Asked Questions</span>
              <h2 className="text-2xl md:text-3xl font-extrabold text-govBlue">Statutory & Platform Guidance</h2>
            </div>

            <div className="space-y-3">
              {faqs.map((faq, idx) => (
                <div key={idx} className="border border-slate-200 rounded-xl overflow-hidden bg-slate-50">
                  <button
                    onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                    className="w-full p-4 text-left font-bold text-govBlue text-xs md:text-sm flex items-center justify-between gap-4 hover:bg-slate-100 transition-colors"
                  >
                    <span>{faq.q}</span>
                    {activeFaq === idx ? (
                      <ChevronUp className="w-4 h-4 text-saffron shrink-0" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                    )}
                  </button>
                  {activeFaq === idx && (
                    <div className="p-4 pt-0 text-xs text-slate-700 leading-relaxed border-t border-slate-200/60 bg-white">
                      {faq.a}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
